name: Test Dynamic Uses

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      node_version: 18.4.0
    steps:
      - uses: actions/checkout@v4

      - name: Test with setup-node
        uses: ./
        id: setup-node
        with:
          uses: actions/setup-node@${{ 'v3' }}
          with: '{
            "node-version": "${{ env.node_version }}",
            "check-latest": false
          }'

      - name: Verify setup-node outputs
        run: |
          echo "Node version: ${{ fromJSON(steps.setup-node.outputs.outputs).node-version }}"
          node -v

      - name: Validate outputs
        run: |
          expected="v${node_version}"
          actual="${{ fromJSON(steps.setup-node.outputs.outputs)['node-version'] }}"
          if [[ "$expected" != "$actual" ]]; then
            echo "::error::output mismatch! expected=$expected, actual=$actual"
            exit 1
          fi
